# Generated by Django 3.0.8 on 2020-08-23 15:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': '订阅', 'verbose_name_plural': '订阅'},
        ),
        migrations.AlterModelOptions(
            name='touch',
            options={'verbose_name': '联系', 'verbose_name_plural': '联系'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.CharField(default='随心所写，记录所想，往后翻起，才有念头！', max_length=300, verbose_name='作者随笔'),
        ),
        migrations.AlterField(
            model_name='post',
            name='saying',
            field=models.CharField(default="If you can't decide an saying who said it, then it was me!", max_length=300, verbose_name='名言引用'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(help_text='请确保图片小于200KB，视频小于6MB！', upload_to='%Y/%m/%d', verbose_name='图片/视频'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_img',
            field=models.ImageField(blank=True, default='', help_text='<b style="color:red;">如果没有上传视频请不要上传这个图片，此图片将用作视频封面。</b>', null=True, upload_to='%Y/%m/%d', verbose_name='视频海报'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='message',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='网站'),
        ),
    ]
